%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\erjav\Desktop\TeideThermal\TeideThermal\teidecode_v1\Thermal_Data.xlsx
%    Worksheet: Conductances_between_nodes
%
% Auto-generated by MATLAB on 07-Apr-2023 12:17:07

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 29);

% Specify sheet and range
opts.Sheet = "Conductances_between_nodes";
opts.DataRange = "B5:AD33";

% Specify column names and types
opts.VariableNames = ["node1", "node2", "node3", "node4", "node5", "node6", "node7", "node8", "node9", "node10", "node11", "node12", "node13", "node14", "node15", "node16", "node17", "node18", "node19", "node20", "node21", "node22", "node23", "node24", "node25", "node26", "node27", "node28", "node29"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
ThermalDataS1 = readtable("C:\Users\erjav\Desktop\TeideThermal\TeideThermal\teidecode_v1\Thermal_Data.xlsx", opts, "UseExcel", false);

%% Convert to output type
ThermalDataS1 = table2array(ThermalDataS1);

%% Clear temporary variables
clear opts