function ThermalDataS1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  THERMALDATAS1 = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  THERMALDATAS1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  THERMALDATAS1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ThermalDataS1 = importfile("C:\Users\erjav\Desktop\TeideThermal\TeideThermal\teidecode_v1\Thermal_Data.xlsx", "Conductances_between_nodes", [5, 33]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Apr-2023 11:57:29

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [5, 33];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 29);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "B" + dataLines(1, 1) + ":AD" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["node1", "node2", "node3", "node4", "node5", "node6", "node7", "node8", "node9", "node10", "node11", "node12", "node13", "node14", "node15", "node16", "node17", "node18", "node19", "node20", "node21", "node22", "node23", "node24", "node25", "node26", "node27", "node28", "node29"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
ThermalDataS1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "B" + dataLines(idx, 1) + ":AD" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    ThermalDataS1 = [ThermalDataS1; tb]; %#ok<AGROW>
end

end